#!/usr/bin/env bash

#********************************************
# Author      : lcdse7en                    *
# E-mail      : 2353442022@qq.com           *
# Create_Time : 2023-12-13 18:21:21         *
# Description :                             *
#********************************************

function open() {
    WORKSPACE=$(hyprctl clients -j | jq -rec ".[] | select(.workspace.name == \"special:$1\") | .workspace.name")

    if [ -z "$WORKSPACE" ]; then
        hyprctl dispatch -- exec "${@:2}"
        hyprctl dispatch togglespecialworkspace "$1"
    elif [ "$WORKSPACE" == "special:$1" ]; then
        hyprctl dispatch togglespecialworkspace "$1"
    fi
}

function main() {
    case "$1" in
    chat)
        open "$1" discord
        ;;
    term)
        open "$1" wezterm start --class scratch-term
        ;;
    calc)
        open "$1" qalculate-gtk
        ;;
    obs)
        open "$1" obs
        ;;
    *)
        echo "no scratchpad with the name of $1"
        ;;
    esac
}

main "$@"
